### ISSUE TITLE
Mock / use logger in unit tests

### ISSUE THREAD

**Issue by tuvokki** [justinkames/vuejs-logger#27]
I'm having some difficulties with using the logger when executing unit tests. I try to use them as described in the testing documentation but it seems to fail.

Here's my component:
```javascript
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js + TypeScript App"/>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import HelloWorld from '@/components/HelloWorld.vue'; // @ is an alias to /src

@Component({
  components: {
    HelloWorld,
  },
})
export default class Home extends Vue {
  private mounted() {
    Vue.$log.debug('Welcome home.');
  }
}
</script>
```
And the test:
```javascript
import { expect } from 'chai';
import { shallowMount, createLocalVue } from '@vue/test-utils';
import Home from '@/views/Home.vue';

import VueLogger from 'vuejs-logger';

const options = {
  isEnabled: true,
  logLevel: 'debug',
  stringifyArguments: false,
  showLogLevel: true,
  showMethodName: true,
  separator: '|',
  showConsoleColors: true,
};

const localVue = createLocalVue();
localVue.use(VueLogger, options);

describe('HelloWorld.vue', () => {
  it('renders props.msg when passed', () => {
    const msg = 'new message';
    const wrapper = shallowMount(Home, { propsData: { msg }, localVue });
    expect(wrapper.text()).to.include(msg);
  });
});
```

In order to let typescript know that `Vue.$log.*` exists I have added a file `shim-vue-logger.d.ts` to my src-folder:
```javascript
import Vue from 'vue';

declare module 'vue/types/vue' {
  interface VueConstructor {
    $log: {
      debug(message: string, trace?: {}): void;
      info(message: string, trace?: {}): void;
      warning(message: string, trace?: {}): void;
      error(message: string, trace?: {}): void;
      fatal(message: string, trace?: {}): void;
    };
  }
}
```

Now, when running `npm run test:unit` I get the following output:
```
 WEBPACK  Compiled successfully in 3956ms

 MOCHA  Testing...



  HelloWorld.vue
    ✓ renders props.msg when passed

  HelloWorld.vue
[Vue warn]: Error in config.errorHandler: "TypeError: Cannot read property 'debug' of undefined"
TypeError: Cannot read property 'debug' of undefined
    at VueComponent.__dirname../node_modules/cache-loader/dist/cjs.js?!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Home.vue?vue&type=script&lang=ts&.Home.mounted (/Users/wouter/development/research/testtest/dist/webpack:/src/views/Home.vue?ee04:19:1)
    at callHook (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2917:1)
    at Object.insert (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4154:1)
    at invokeInsertHook (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5956:1)
    at VueComponent.patch [as __patch__] (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:6175:1)
    at VueComponent.Vue._update (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2656:1)
    at VueComponent.updateComponent (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2784:1)
    at Watcher.get (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:3138:1)
    at new Watcher (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:3127:1)
    at mountComponent (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2791:1)
    at VueComponent.__dirname../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:7995:1)
    at mount (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:5645:1)
    at shallowMount (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:5690:1)
    at Context.<anonymous> (/Users/wouter/development/research/testtest/dist/webpack:/tests/unit/Home.spec.ts:23:1)
    at callFn (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runnable.js:372:21)
    at Test.Runnable.run (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runnable.js:364:7)
    at Runner.runTest (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:455:10)
    at /Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:573:12
    at next (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:369:14)
    at /Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:379:7
    at next (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:303:14)
    at Immediate.<anonymous> (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:347:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'debug' of undefined"

found in

---> <Home> at src/views/Home.vue
       <Root>
TypeError: Cannot read property 'debug' of undefined
    at VueComponent.__dirname../node_modules/cache-loader/dist/cjs.js?!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Home.vue?vue&type=script&lang=ts&.Home.mounted (/Users/wouter/development/research/testtest/dist/webpack:/src/views/Home.vue?ee04:19:1)
    at callHook (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2917:1)
    at Object.insert (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4154:1)
    at invokeInsertHook (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5956:1)
    at VueComponent.patch [as __patch__] (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:6175:1)
    at VueComponent.Vue._update (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2656:1)
    at VueComponent.updateComponent (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2784:1)
    at Watcher.get (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:3138:1)
    at new Watcher (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:3127:1)
    at mountComponent (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2791:1)
    at VueComponent.__dirname../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:7995:1)
    at mount (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:5645:1)
    at shallowMount (/Users/wouter/development/research/testtest/dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:5690:1)
    at Context.<anonymous> (/Users/wouter/development/research/testtest/dist/webpack:/tests/unit/Home.spec.ts:23:1)
    at callFn (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runnable.js:372:21)
    at Test.Runnable.run (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runnable.js:364:7)
    at Runner.runTest (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:455:10)
    at /Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:573:12
    at next (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:369:14)
    at /Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:379:7
    at next (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:303:14)
    at Immediate.<anonymous> (/Users/wouter/development/research/testtest/node_modules/mocha/lib/runner.js:347:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
    1) renders props.msg when passed


  1 passing (190ms)
  1 failing

  1) HelloWorld.vue
       renders props.msg when passed:
     TypeError: Cannot read property 'debug' of undefined
      at VueComponent.__dirname../node_modules/cache-loader/dist/cjs.js?!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Home.vue?vue&type=script&lang=ts&.Home.mounted (dist/webpack:/src/views/Home.vue?ee04:19:1)
      at callHook (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2917:1)
      at Object.insert (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4154:1)
      at invokeInsertHook (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5956:1)
      at VueComponent.patch [as __patch__] (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:6175:1)
      at VueComponent.Vue._update (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2656:1)
      at VueComponent.updateComponent (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2784:1)
      at Watcher.get (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:3138:1)
      at new Watcher (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:3127:1)
      at mountComponent (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2791:1)
      at VueComponent.__dirname../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (dist/webpack:/node_modules/vue/dist/vue.runtime.esm.js:7995:1)
      at mount (dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:5645:1)
      at shallowMount (dist/webpack:/node_modules/@vue/test-utils/dist/vue-test-utils.js:5690:1)
      at Context.<anonymous> (dist/webpack:/tests/unit/Home.spec.ts:23:1)



 MOCHA  Tests completed with 1 failure(s)

 ERROR  mocha-webpack exited with code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testtest@0.1.0 test:unit: `vue-cli-service test:unit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testtest@0.1.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wouter/.npm/_logs/2018-10-20T09_04_03_945Z-debug.log
```

Am I missing something here? Is this shim included in the actual build but not in the testbuild?

**Comment by tuvokki** [comment]
Mocking the $log also results in the same error, see following test:
```javascript
import { expect } from 'chai';
import { shallowMount, createLocalVue } from '@vue/test-utils';
import Home from '@/views/Home.vue';

const $log = {
  debug(message: string, trace?: {}): void {
    //
  },
  info(message: string, trace?: {}): void {
    //
  },
  warning(message: string, trace?: {}): void {
    //
  },
  error(message: string, trace?: {}): void {
    //
  },
  fatal(message: string, trace?: {}): void {
    //
  },
};

describe('HelloWorld.vue', () => {
  it('renders props.msg when passed', () => {
    const msg = 'new message';
    const wrapper = shallowMount(Home, {
      propsData: { msg },
      mocks: {
        $log,
      },
    });
    expect(wrapper.text()).to.include(msg);
  });
});
```

**Comment by tuvokki** [comment]
A combination of these also to no avail:
```javascript
import { expect } from 'chai';
import { shallowMount, createLocalVue } from '@vue/test-utils';
import Home from '@/views/Home.vue';

const $log = {
  debug(message: string, trace?: {}): void {
    //
  },
  info(message: string, trace?: {}): void {
    //
  },
  warning(message: string, trace?: {}): void {
    //
  },
  error(message: string, trace?: {}): void {
    //
  },
  fatal(message: string, trace?: {}): void {
    //
  },
};

const localVue = createLocalVue();
localVue.prototype.$log = $log;

describe('HelloWorld.vue', () => {
  it('renders props.msg when passed', () => {
    const msg = 'new message';
    const wrapper = shallowMount(Home, { propsData: { msg }, localVue });
    expect(wrapper.text()).to.include(msg);
  });
});
```
Clearly I'm missing _some_ point here, I just don't know which.

**Comment by tuvokki** [comment]
To answer my own question.
I have changed the shim to the following (in order to make TypeScript happy):
```javascript
import Vue from 'vue';

declare module 'vue/types/vue' {
  interface VueConstructor {
    $log: {
      debug(message: string, trace?: {}): void;
      info(message: string, trace?: {}): void;
      warning(message: string, trace?: {}): void;
      error(message: string, trace?: {}): void;
      fatal(message: string, trace?: {}): void;
    };
  }

  interface Vue {
    $log: {
      debug(message: string, trace?: {}): void;
      info(message: string, trace?: {}): void;
      warning(message: string, trace?: {}): void;
      error(message: string, trace?: {}): void;
      fatal(message: string, trace?: {}): void;
    };
  }
}
```

And now I can use the logger on a per class based usage instead `this.$log` of the static usage `Vue.$log` in my class based Components:
```javascript
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js + TypeScript App"/>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import HelloWorld from '@/components/HelloWorld.vue'; // @ is an alias to /src

@Component({
  components: {
    HelloWorld,
  },
})
export default class Home extends Vue {
  private mounted() {
    Vue.$log.debug('Welcome home.');
  }
}
</script>
```

This solves the original question and this can be closed.

**Comment by justinkames** [comment]
Awesome @tuvokki !
