### ISSUE TITLE
logger

### ISSUE THREAD

**Issue by fatb0000** [justinkames/vuejs-logger#3]
could logger output with real  filename + line number ?
e.g. 
in aaa.vue: 
line 5: this.$log.info('test')

output:
test          [aaa.vue:5]

**Comment by justinkames** [comment]
This is not possible unless you do not have a SPA set up / use Webpack. During development the stack trace from where the method name is retrieved looks like this :

```
Error
    at getMethodName (webpack-internal:///41:75:21)
    at Object.logger.(anonymous function).args [as error] (webpack-internal:///41:19:40)
    at Vue$3.created (webpack-internal:///26:38:19)
    at callHook (webpack-internal:///1:2818:21)
    at Vue$3.Vue._init (webpack-internal:///1:4477:5)
    at new Vue$3 (webpack-internal:///1:4572:8)
    at eval (webpack-internal:///26:24:1)
    at Object.<anonymous> (http://localhost:8082/app.js:899:1)
    at __webpack_require__ (http://localhost:8082/app.js:679:30)
    at fn (http://localhost:8082/app.js:89:20)
```
Unfortunately it's not possible to retrieve the Vue component name / filename from this ( because it's minified ). If you have any suggestions on how to achieve this I'm happy to hear them!
